import { Layout } from "@/components/Layout";
import { Link } from "react-router-dom";
import { Linkedin } from "lucide-react";

const paragraphs = [
"Regolare l’intelligenza artificiale non basta. Servono infrastrutture controllabili, sperimentazioni accessibili e una strada che permetta all’innovazione di entrare davvero nella Pubblica Amministrazione.",
"L’Europa ha costruito il cancello normativo. Ora deve collegare infrastrutture, governo dei procedimenti e accesso reale alla sperimentazione.",
"Ho letto oggi una riflessione pubblicata da Lara Stuart-Mueller, fondatrice di PromptLedger.co e Vela Protocol, che utilizza un’immagine particolarmente efficace per descrivere la prossima sfida tecnologica europea: quella del giardino recintato. Il punto di osservazione è particolarmente interessante perché Stuart-Mueller colloca il proprio lavoro nel campo delle architetture di AI Governance, in quello che definisce il “deterministic boundary”. Le piattaforme chiuse, sostiene, non sono necessariamente un male in sé. Un recinto può proteggere la privacy, la sicurezza, la continuità e la fiducia. Il problema nasce quando il cancello è controllato da soggetti privati, secondo regole invisibili, senza responsabilità pubblica e senza la possibilità di ricostruire il modo in cui quel potere è stato esercitato.",
"La proposta è quindi quella di non abbattere il giardino, ma di sottoporre il cancello a un controllo democratico. È una metafora convincente, soprattutto nel momento in cui l’Europa si prepara a rendere pienamente operativo il proprio modello di regolazione dell’intelligenza artificiale. Eppure, proprio quella metafora apre una domanda ulteriore: possiamo davvero governare il cancello se non controlliamo il terreno sul quale è stato costruito?",
"Possiamo davvero governare il cancello se non controlliamo il terreno sul quale è stato costruito?",
"L’Unione europea ha certamente compiuto una scelta politica importante. Con l’AI Act ha stabilito divieti, classificazioni del rischio, obblighi di documentazione, requisiti di supervisione umana e responsabilità distribuite lungo la catena del valore. Ha affermato, in sostanza, che l’intelligenza artificiale non può entrare nella vita delle persone e delle organizzazioni come una forza priva di mandato, di limiti e di possibilità di controllo.",
"Ma una legge non costruisce, da sola, una capacità tecnologica. Stabilire le condizioni alle quali un sistema può operare non significa possedere il cloud sul quale quel sistema viene eseguito, i modelli che utilizza, la capacità di calcolo necessaria per svilupparlo, l’hardware su cui si fonda o il capitale industriale che ne sostiene la crescita. L’Europa sta cercando di esercitare una sovranità normativa su una filiera tecnologica che, in larga parte, continua a dipendere da operatori non europei.",
"Questa è forse la contraddizione più profonda del nostro modello. Possiamo scrivere regole democratiche per il cancello, ma se l’infrastruttura, gli standard di fatto e le principali piattaforme appartengono ad altri, la nostra capacità di governo resta inevitabilmente parziale. Il luogo fisico in cui si trova un server è importante, ma non esaurisce il concetto di sovranità. Un dato può essere conservato in Italia e dipendere comunque da software, componenti, modelli, licenze o poteri decisionali collocati fuori dall’Europa. La residenza del dato è soltanto uno dei livelli del controllo; gli altri riguardano la giurisdizione, la continuità operativa, le chiavi di sicurezza, l’autonomia dello stack tecnologico e la possibilità concreta di sostituire un fornitore senza perdere la capacità di funzionare.",
"Questo non significa che in Italia non si stia costruendo nulla. Il Polo Strategico Nazionale rappresenta un passaggio concreto verso una maggiore tutela dei dati e dei servizi critici della Pubblica Amministrazione. Parallelamente, la nuova IT4LIA AI Factory, ospitata e gestita dal CINECA a Bologna, dovrebbe rafforzare la capacità di calcolo disponibile per ricerca, imprese, startup e settore pubblico. Gli investimenti, quindi, esistono. Il punto è capire se questi elementi diventeranno parti di una strategia industriale coerente oppure resteranno grandi infrastrutture scarsamente collegate ai percorsi attraverso i quali nasce e viene sperimentata l’innovazione.",
"Una direzione istituzionale comincia, in realtà, a emergere. In un intervento intitolato IA come “cantiere”: modelli, dati e nuove potenzialità al servizio della persona, Mario Nobile, Direttore generale di AgID, ha descritto l’intelligenza artificiale nella Pubblica Amministrazione non come un oggetto finito, ma come un sistema in continua costruzione. La sua proposta ruota intorno a un orchestratore capace di coordinare tre componenti: i modelli, le pipeline di collegamento ai dati pubblici e gli strumenti applicativi dimensionati sulle necessità dell’ente.",
"Non si tratta, quindi, di imporre un unico motore monolitico e identico a tutte le amministrazioni. Si tratta di consentire a ciascun contesto amministrativo di combinare tecnologie diverse senza perdere il controllo sull’insieme. Nobile collega questa impostazione anche al disaccoppiamento tecnologico: poter utilizzare le soluzioni migliori senza rimanere prigionieri di un singolo fornitore, mantenendo il controllo dei dati e la possibilità di cambiare componenti nel tempo. È una visione importante, perché sposta il dibattito dal singolo modello alla capacità pubblica di orchestrare una pluralità di risorse.",
"Ma proprio questa visione apre una quarta domanda. Coordinare modelli, dati e strumenti non significa ancora governare il procedimento nel quale essi operano. Lo stesso modello, collegato agli stessi dati e agli stessi strumenti, può produrre conseguenze profondamente diverse a seconda del ruolo del soggetto che lo utilizza, delle condizioni che autorizzano l’azione, delle eccezioni previste, dello stato della pratica e del momento in cui deve intervenire una persona. All’orchestrazione tecnologica deve quindi affiancarsi un livello di governance procedurale, capace di stabilire non soltanto quale tecnologia usare, ma entro quale mandato, secondo quali regole e lasciando quali prove.",
"In questa prospettiva, la scelta di partire da piccoli applicativi di intelligenza artificiale, circoscritti a una singola amministrazione o a uno specifico procedimento e ospitati su un’infrastruttura nazionale, non è necessariamente un errore. Può essere, al contrario, il punto di partenza più concreto. Una pubblica amministrazione potrebbe selezionare un procedimento delimitato, sperimentare una soluzione in un ambiente controllato, misurarne i risultati e verificare sul campo la sicurezza, la tracciabilità, l’intervento umano e la conformità normativa prima di valutarne l’estensione.",
"Un applicativo isolato non è automaticamente un silo. Diventa un silo quando nasce senza interoperabilità, senza possibilità di riuso, senza una logica di estensione e senza un’architettura capace di trasferire ciò che è stato appreso ad altri procedimenti. La differenza non dipende quindi dalla dimensione iniziale del progetto, ma dalla direzione nella quale è stato progettato. Un POC limitato può essere il primo modulo di una capacità pubblica più ampia; cento applicativi incompatibili, invece, possono trasformarsi in cento nuove dipendenze tecnologiche.",
"Ed è qui che emerge la seconda contraddizione, quella che una piccola startup incontra non nei documenti programmatici, ma nella realtà. Alle imprese innovative viene chiesto di sviluppare sistemi affidabili, sicuri, documentati, tracciabili, rispettosi dell’AI Act e capaci di integrarsi con infrastrutture qualificate. Sono richieste legittime. Ma quando quella stessa impresa cerca un’amministrazione disponibile a sperimentare un POC circoscritto, controllato e misurabile, l’accesso diventa estremamente difficile.",
"Si crea così un paradosso quasi perfetto: per entrare nel mercato pubblico occorre dimostrare una sperimentazione, ma per ottenere una sperimentazione viene spesso richiesta una presenza già consolidata nel mercato pubblico. La tecnologia deve avere referenze, ma non trova il luogo nel quale costruirle. Deve dimostrare risultati, ma non può accedere al contesto nel quale quei risultati potrebbero essere verificati. Deve essere pronta per la scala prima ancora di avere avuto la possibilità di realizzare il primo caso d’uso istituzionale.",
"Non è un’ipotesi astratta. È quanto emerge anche dal percorso di CAELO. Fuori dall’Italia la piattaforma è stata ascoltata e valutata innanzitutto per ciò che già è: una tecnologia sviluppata e operativa, non una semplice idea ancora da incubare. A Parigi, proprio in ragione della sua maturità tecnologica e progettuale, CAELO è stata ricondotta alla Graduate Zone dell’ecosistema STATION F, oltre la fase ordinaria di incubazione. In Irlanda, dopo un confronto diretto, Enterprise Ireland ha comunicato formalmente al team di aver trovato innovativa la proposta.",
"Questi riconoscimenti non equivalgono ancora a un’adozione o a una commessa pubblica, dimostrano però qualcosa di importante: quando esiste una porta di accesso, anche un prodotto indipendente, nato fuori dai grandi gruppi industriali, può essere ascoltato e valutato per la qualità e la maturità della tecnologia. La domanda scomoda è perché un prodotto nato e sviluppato in Italia riesca a ottenere questo tipo di attenzione all’estero, mentre nel proprio Paese incontra ancora enormi difficoltà persino nell’accedere a un POC circoscritto.",
"La risposta di Enterprise Ireland rende ancora più evidente la posta in gioco. Il sostegno alle startup ad alto potenziale è subordinato al loro radicamento nel Paese: sede centrale e controllo in Irlanda, fondatori e vertici residenti, attività svolta stabilmente sul territorio, capacità di creare occupazione e di raggiungere rapidamente una dimensione internazionale. Non è un incentivo indiscriminato al trasferimento e non viene presentato come tale; è una politica industriale selettiva, che collega il sostegno pubblico alla localizzazione del centro decisionale e del valore futuro.",
"L’Irlanda, in altre parole, non cerca soltanto persone qualificate. Cerca imprese, proprietà intellettuale, capacità decisionale, posti di lavoro e gettito. Comprende che, quando un prodotto tecnologico promettente mette radici, intorno a esso può formarsi un’intera capacità industriale. L’Italia rischia invece di compiere il percorso opposto: contribuire alla nascita della competenza e del prodotto, ma non offrire il primo spazio nel quale sperimentarlo e costringerlo così a cercare altrove le condizioni per crescere.",
"Il cosiddetto sogno americano non consiste soltanto nell’immagine romantica del prodotto costruito in un garage e arrivato fino alla Borsa. Consiste nell’esistenza di un sistema capace di riconoscere che una tecnologia nata ai margini degli apparati consolidati può diventare un’impresa, un mercato e, infine, un asset strategico. Non ogni garage conduce a Wall Street, naturalmente; ma tra il garage e il mercato esiste una successione di porte — sperimentazione, capitale, primi clienti, acquisto pubblico e scala — che non pretende dall’innovatore di essere già un grande operatore prima ancora di cominciare.",
"L’Italia potrebbe compiere un grande salto di qualità se costruisse una catena analoga, coerente con il proprio ordinamento e con il modello europeo. Continuiamo giustamente a parlare di fuga dei cervelli, ma oggi dobbiamo riconoscere anche un altro rischio: la fuga dei prodotti strategici. Quando una startup italiana deve cercare all’estero il primo luogo in cui sperimentare, il primo partner industriale o il primo mercato disposto ad ascoltarla, non si spostano soltanto le persone. Possono migrare la proprietà intellettuale, le competenze accumulate, i futuri posti di lavoro, le relazioni industriali, il gettito e la capacità del Paese di incidere sugli standard tecnologici.",
"È una perdita più silenziosa della fuga dei talenti, perché spesso avviene prima che il prodotto abbia generato un’azienda visibile e un’occupazione misurabile. Quando ce ne accorgiamo, quella tecnologia ha già trovato altrove il capitale, l’infrastruttura e il mercato necessari per crescere. Il paradosso è che l’Italia può aver contribuito alla formazione delle persone e alla nascita dell’idea, per poi lasciare ad altri Paesi la trasformazione di quell’idea in capacità industriale.",
"I grandi operatori possono sostenere i costi della conformità, partecipare a procedure complesse, mantenere strutture dedicate alle gare e assorbire tempi decisionali molto lunghi. Una startup, anche quando possiede una tecnologia già sviluppata, non dispone necessariamente dello stesso apparato finanziario, amministrativo e relazionale. Il rischio è che una regolamentazione pensata per rendere il mercato più sicuro finisca per rafforzare proprio gli operatori già dominanti, non perché siano sempre i più innovativi, ma perché sono gli unici in grado di sostenere il costo dell’ingresso.",
"Gli strumenti giuridici, almeno sulla carta, non mancano. Gli appalti innovativi e gli appalti pre-commerciali consentono alla Pubblica Amministrazione di esprimere un bisogno funzionale e di chiedere al mercato di proporre, sviluppare e sperimentare soluzioni nuove. Il problema è che questi strumenti restano ancora eccezionali rispetto alla dimensione del bisogno. Non costituiscono una porta ordinaria, riconoscibile e continuativa attraverso la quale una piccola realtà possa presentare una tecnologia pronta, ottenere una valutazione trasparente e, se la valutazione è positiva, accedere a una sperimentazione limitata.",
"Per questo non credo che la questione possa essere ricondotta soltanto alla mancanza di capitali. In Italia e in Europa vengono mobilitate risorse molto rilevanti per la trasformazione digitale, il cloud, la ricerca e l’intelligenza artificiale. Il problema riguarda anche la loro destinazione, la continuità delle iniziative e la capacità di collegare l’investimento infrastrutturale alla domanda concreta delle amministrazioni e all’offerta delle imprese emergenti. Possiamo finanziare un’infrastruttura, un programma di accelerazione e una strategia nazionale, ma se tra questi tre elementi non esiste un passaggio operativo, la startup resta fuori e l’amministrazione continua ad acquistare attraverso le stesse filiere consolidate.",
"Lo stiamo osservando direttamente nel percorso sviluppato con CAELO. Abbiamo lavorato per tradurre i principi dell’AI Act in un’architettura capace di governare regole, ruoli, condizioni, eccezioni, interventi umani e prove del procedimento. Non si tratta di aggiungere un ulteriore modello generativo alla Pubblica Amministrazione, ma di affrontare una domanda diversa: in quale procedimento opera l’intelligenza artificiale, chi le attribuisce il potere di agire, quali limiti incontra e come possiamo dimostrare, successivamente, ciò che è realmente accaduto?",
"Questa esperienza ci ha mostrato che la conformità non può essere soltanto documentale. Deve diventare operativa. Un sistema non è governato perché esiste una dichiarazione che lo descrive come tale; è governato quando le regole, le autorizzazioni, i passaggi, le eccezioni e la supervisione sono incorporati nel modo in cui il procedimento viene eseguito e quando ogni decisione rilevante lascia una prova verificabile.",
"Un POC ospitato sul Polo Strategico Nazionale, applicato a un solo procedimento e costruito con questa logica, potrebbe rappresentare un laboratorio concreto di sovranità tecnologica e procedurale. Sarebbe piccolo nella dimensione, ma non nell’ambizione. Permetterebbe di verificare come un’infrastruttura nazionale, una normativa europea e un’architettura di governo possano incontrarsi dentro un caso reale, senza chiedere all’amministrazione di sostituire immediatamente i propri sistemi e senza trasformare la sperimentazione in un progetto indefinito.",
"È questo il passaggio che oggi sembra mancare. Non un altro principio generale, non l’ennesima dichiarazione sulla necessità di un’intelligenza artificiale affidabile, ma una politica dell’accesso alla sperimentazione. Servirebbero procedure semplici e periodiche attraverso le quali le amministrazioni possano pubblicare problemi circoscritti, selezionare soluzioni sulla base della loro capacità effettiva, ospitarle in ambienti controllati e misurarne gli esiti. Il POC dovrebbe diventare uno strumento ordinario di conoscenza e acquisto pubblico, non una concessione informale ottenuta soltanto attraverso relazioni già esistenti.",
"La prossima leadership tecnologica europea non nascerà dunque dalla sola regolamentazione e neppure dalla sola costruzione di nuovi data center. Nascerà se l’Europa riuscirà a collegare diritto, infrastruttura, capacità industriale e accesso al mercato. Le regole devono poter essere eseguite, le infrastrutture devono poter essere utilizzate e le innovazioni devono poter essere provate prima che venga loro chiesto di essere già grandi.",
"Il cancello democratico immaginato nell’articolo può essere un’immagine del futuro europeo, ma a tre condizioni: che l’Europa controlli progressivamente il terreno tecnologico sul quale quel cancello viene costruito, che sappia rendere verificabili le regole attraverso cui si apre e si chiude, e che non lasci fuori, per mancanza di una procedura accessibile, proprio coloro che potrebbero contribuire a costruirlo.",
"Altrimenti continueremo a essere il continente che scrive le regole del giardino, mentre altri ne possiedono il suolo, gli strumenti e le chiavi."
];

const references = [
"Lara Stuart-Mueller. Post LinkedIn: “Perché l’Europa potrebbe apportare il prossimo grande cambiamento tecnologico”, pubblicato il 20 luglio 2026.",
"Unione europea. Regolamento (UE) 2024/1689 — Artificial Intelligence Act.",
"Dipartimento per la trasformazione digitale. Polo Strategico Nazionale.",
"EuroHPC Joint Undertaking. IT4LIA AI Factory: nuova infrastruttura italiana ottimizzata per l’intelligenza artificiale.",
"Mario Nobile, Direttore generale AgID. IA come “cantiere”: modelli, dati e nuove potenzialità al servizio della persona.",
"Agenda Digitale. Governare l’IA nella PA: la strategia di AgID.",
"Agenzia per l’Italia Digitale. Appalti innovativi."
];

export default function ArticoloCancelloEuropeo() {
  const shareOnLinkedIn = () => {
    const linkedInUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`;
    window.open(linkedInUrl, "_blank", "noopener,noreferrer,width=760,height=720");
  };

  return (
    <Layout>
      <div className="min-h-screen bg-[#f2eee4] text-[#171714]">
        <main className="mx-auto max-w-[1180px] px-4 py-8 md:px-8 md:py-12">
          <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
            <Link to="/la-voce" className="inline-flex border-b border-black pb-1 text-xs font-semibold uppercase tracking-[0.18em]">← La Voce di CAELO</Link>
            <button type="button" onClick={shareOnLinkedIn} className="inline-flex items-center gap-2 border border-black bg-[#faf7ef] px-4 py-2 text-sm font-semibold transition-colors hover:bg-black hover:text-[#faf7ef]">
              <Linkedin className="h-4 w-4" aria-hidden="true" /> Condividi su LinkedIn
            </button>
          </div>

          <article className="mt-6 border border-black/70 bg-[#faf7ef] px-5 py-8 md:px-14 md:py-14">
            <header className="border-b border-black/50 pb-8 text-center">
              <p className="text-xs font-semibold uppercase tracking-[0.24em]">Sovranità tecnologica · Pubblica Amministrazione</p>
              <h1 className="mx-auto mt-5 max-w-5xl font-serif text-5xl font-semibold leading-[0.98] md:text-7xl">Il cancello europeo nel giardino tecnologico degli altri</h1>
              <p className="mx-auto mt-6 max-w-4xl font-serif text-2xl italic leading-snug text-black/70">Regolare l’intelligenza artificiale non basta. Servono infrastrutture controllabili, sperimentazioni accessibili e una strada che permetta all’innovazione di entrare davvero nella Pubblica Amministrazione.</p>
              <p className="mt-6 text-sm">Di Claudia Catania · 21 luglio 2026</p>
            </header>

            <div className="mx-auto mt-10 max-w-3xl font-serif text-[19px] leading-8">
              {paragraphs.map((paragraph, index) => (
                <p key={`${index}-${paragraph.slice(0, 32)}`} className={index === 0 ? "first-letter:float-left first-letter:mr-2 first-letter:text-7xl first-letter:leading-[0.8]" : "mt-5"}>{paragraph}</p>
              ))}

              <section className="mt-12 border-t border-black/50 pt-7">
                <h2 className="font-serif text-3xl font-semibold md:text-4xl">Riferimenti essenziali</h2>
                <ul className="mt-5 space-y-3 text-base leading-7">
                  {references.map((reference) => <li key={reference}>— {reference}</li>)}
                </ul>
                <p className="mt-6 text-sm italic text-black/65">Documento editoriale destinato alla pubblicazione come newsletter LinkedIn. I collegamenti sono stati inseriti come riferimenti di approfondimento.</p>
              </section>
            </div>

            <footer className="mt-12 border-t border-black/50 pt-7">
              <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end">
                <div><p className="font-serif text-xl font-semibold">Claudia Catania</p><p className="mt-2 text-sm text-black/70">Co-Founder of CAELO</p></div>
                <button type="button" onClick={shareOnLinkedIn} className="inline-flex shrink-0 items-center justify-center gap-2 border border-black px-4 py-2 text-sm font-semibold transition-colors hover:bg-black hover:text-[#faf7ef]"><Linkedin className="h-4 w-4" aria-hidden="true" /> Pubblica su LinkedIn</button>
              </div>
            </footer>
          </article>
        </main>
      </div>
    </Layout>
  );
}
